[build]
  command = "npm run build"
  publish = "dist"

[context.production]
  command = "npm run build && cd admin && npm run build"

# Main site redirects
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false
  
# Admin panel build settings  
[build.processing.admin]
  command = "cd admin && npm run build"
  publish = "admin/dist"
  
# Admin panel redirects
[[redirects]]
  from = "/admin/*"
  to = "/admin/index.html"
  status = 200
  force = true
